apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'portworx'
      target_groups:
        # This configures Prometheus to get Portworx stats.   Replace "Portworx_Node_IP" with one of your Portworx node IP 
      - targets:
        - "Portworx_Node_IP":9001
        
