---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
   name: portworx-prometheus
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: prometheus-001
   annotations:
     volume.beta.kubernetes.io/storage-class: portworx-prometheus
 spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 30900
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:0.19.2
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus/data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data
        persistentVolumeClaim:
          claimName: prometheus-001
