{
 "title": "Portworx Node Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "px_cluster_cpu_percent" },
   { "name": "Instances", "query": "px_cluster_cpu_percent" }
  ]
 },
 "panels": [
  { "title": "Nodes and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Alert List",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 1 },
   "targets": [
    { "labelSelector": "alertname, issue, cluster,node", "target": "Query", "type": "table" }
   ]
  },
  {
   "title": "Members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size{cluster=~\"$Cluster\"}) "
    }
   ]
  },
  {
   "title": "Storage Providers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online{cluster=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Instances \"$Instances\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Usage: $tag_cluster - $tag_node",
     "expr": "px_cluster_cpu_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "cluster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_cpu_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Usage: $tag_node",
     "expr": "px_cluster_memory_utilized_percent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_memory_utilized_percent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Memory Usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Network TX/RX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "IO Bytes TX",
     "expr": "px_network_io_bytessent{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes TX",
     "measurement": "px_network_io_bytessent",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Bytes RX",
     "expr": "px_network_io_received_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bytes RX",
     "measurement": "px_network_io_received_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_cluster_disk_total_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_cluster_disk_utilized_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "irate(px_disk_stats_read_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "irate(px_disk_stats_write_bytes{cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "Cluster Disk Total",
     "expr": "px_disk_stats_read_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_total_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "Cluster Disk Used",
     "expr": "px_disk_stats_write_latency_seconds{cluster=~\"$Cluster\",instance=~\"$Instances\"}",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{cluster}}{{instance}}",
     "measurement": "px_cluster_disk_utilized_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "PWX  Disk IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_read_seconds {cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Read {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    },
    {
     "alias": "IO Pending",
     "expr": "irate(px_disk_stats_write_seconds {cluster=~\"$Cluster\",instance=~\"$Instances\"}[5m])",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Write  {{cluster}} {{instance}}",
     "measurement": "px_cluster_pendingio",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
     ]
    }
   ]
  }
 ]
}