{
 "title": "Portworx Volume Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "volumeid",
    "label": "VolumeID",
    "query": "label_values(px_volume_usage_bytes,volumeid)"
   }
  ]
 },
 "panels": [
  { "title": "PX Volume Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume HA Level",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "px_volume_halevel", "legendFormat": "volumeid - {{volumeid}}" }
   ]
  },
  {
   "title": "Volume Sizes",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "px_volume_capacity_bytes",
     "legendFormat": "volumeid - {{volumeid}} - on - {{host}}}"
    }
   ]
  },
  {
   "title": "Volume Usage Status",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
     "legendFormat": "volumeid - {{volumeid}}"
    }
   ]
  },
  {
   "title": "IO Depth & Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume IO Depth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "px_volume_depth_io{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Volume Space Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(px_volume_usage_bytes/px_volume_capacity_bytes)*100",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Device IO Depth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "px_volume_dev_depth_io{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Volume FS Space Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(px_volume_fs_usage_bytes/px_volume_fs_capacity_bytes)*100",
       "legendFormat": "{{volumeid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_volume_dev_write_latency_seconds{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}_write"
      }
     ]
    },
    {
     "title": "Device Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_volume_dev_read_latency_seconds{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}_read"
      }
     ]
    },
    {
     "title": "Volume Write Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_volume_vol_write_latency_seconds{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Volume Read Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_volume_vol_read_latency_seconds{volumeid=~\"$volumeid\"}",
       "legendFormat": "{{volumeid}}_write"
      }
     ]
    },
    {
     "title": "Pool Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "px_pool_stats_pool_write_latency_seconds{pool=~\"$pool\"}",
       "legendFormat": "{{pool}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Write Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(px_volume_dev_writethroughput{volumeid=~\"$volumeid\"}[5m]) ",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Device Read Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(px_volume_dev_readthroughput{volumeid=~\"$volumeid\"}[5m]) ",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Volume Write Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(px_volume_writethroughput{volumeid=~\"$volumeid\"}[5m]) ",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Volume Read Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(px_volume_readthroughput{volumeid=~\"$volumeid\"}[5m]) ",
       "legendFormat": "{{volumeid}}"
      }
     ]
    },
    {
     "title": "Pool Write Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      {
       "format": "bytes",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(px_pool_stats_pool_writethroughput{pool=~\"pool\"}[5m]) ",
       "legendFormat": "{{pool}}"
      }
     ]
    },
    {
     "title": "Volume IOs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "IO/second read (-) / write (+)" }
     ],
     "targets": [
      { "expr": "irate(px_volume_iops[5m]) ", "legendFormat": "{{volumeid}}_iops" }
     ]
    }
   ]
  }
 ]
}