{
 "title": "Super Hidden Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Long Reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_reads", "legendFormat": "{{volumeid}}" }
   ]
  },
  {
   "title": "Bytes Flushed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "px_pool_stats_pool_flushed_bytes",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Long Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_writes", "legendFormat": "{{volumeid}}" }
   ]
  },
  {
   "title": "Pool Flush MS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    { "expr": "px_pool_stats_flushms", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Long Flushes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_volume_num_long_flushes", "legendFormat": "{{volumeid}}" }
   ]
  },
  {
   "title": "Pool Number of Flushes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "px_pool_stats_pool_num_flushes", "legendFormat": "{{pool}}" }
   ]
  }
 ]
}